name: Bug Report
description: Report a bug or issue with the library
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide as much detail as possible.

  - type: input
    id: version
    attributes:
      label: Library Version
      description: Which version of the library are you using?
      placeholder: e.g., 1.2.3
    validations:
      required: true

  - type: input
    id: php-version
    attributes:
      label: PHP Version
      description: Which PHP version are you using?
      placeholder: e.g., 8.1.0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Call method X with parameters Y
        2. Observe error Z
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe actual behavior...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Example
      description: Minimal code example that demonstrates the issue
      render: php
      placeholder: |
        <?php
        // Your code here
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional context or screenshots
      placeholder: Add any other context about the problem here...
    validations:
      required: false