name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of what you want to happen
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Alternative solutions or features you've considered
      placeholder: I also considered...
    validations:
      required: false

  - type: textarea
    id: api-example
    attributes:
      label: API Example
      description: How would you like the API to work?
      render: php
      placeholder: |
        <?php
        // Example usage
        $api->newFeature->doSomething();
    validations:
      required: false

  - type: checkboxes
    id: scope
    attributes:
      label: Scope
      description: What areas does this feature affect?
      options:
        - label: Deals API
        - label: Contacts API
        - label: Accounts API
        - label: Custom Objects API
        - label: Custom Fields API
        - label: Core functionality
        - label: Documentation
        - label: Testing

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my work
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional context, screenshots, or links
      placeholder: Add any other context about the feature here...
    validations:
      required: false